M48
; DRILL file {KiCad 9.0.7} date 2026-03-30T11:08:42+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-30T11:08:42+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.500
%
G90
G05
T1
X176.7Y-77.983
X183.7Y-77.983
T2
X122.73Y-87.345
X148.23Y-87.345
T3
X116.0Y-69.0
X116.0Y-103.0
X186.0Y-69.0
X186.0Y-103.0
M30
